spring:
  application:
    name: promotions-microservice

server:
  port: ${PORT:${SERVER_PORT:8081}}

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://eureka-service:8761/eureka

  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}